[project]
name = "lzits-nodes"
description = "ComfyUI custom nodes for text/string manipulation including splitting strings into batches, appending/prepending text, picking items from lists by index, and multi-output LoRA selection."
version = "1.0.17"
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/lzitser23/lzits-nodes"  

[tool.comfy]
PublisherId = "lzitser"  
DisplayName = "lzits Nodes"
Icon = "" # add later if i want
